---
ansible-navigator:
ansible:
   inventory:
      entries:
      - inventory
execution-environment:
   container-engine: docker
   enabled: true
   image: harbor.test.local/library/f5_business_development/f5_ee
   #image: quay.io/f5_business_development/f5_ee_static_build:latest  # This is a backup image with a static build of collections known to work
   pull:
      policy: missing