---
- hosts: master
  gather_facts: false
  become: true
  
  vars_files:
    - vars/charts/helm_charts.yaml
  
  vars:
    package_state: absent
    kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Deploy Helm Charts
      import_role:
        name: deploy_charts