- name: Create namespace (if not exists)
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item.namespace }}"
    state: "{{ package_state }}"
  loop: "{{ applications }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.namespace != "default"

- name: Deploy applications
  include_tasks: deploy_app.yaml
  loop: "{{ applications }}"
  loop_control:
    loop_var: app


